// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8bY0DDR9CFPqf-p-pSchMHC-UI05ZDEs',
    appId: '1:485307703797:web:d78e695125df3db69b00bc',
    messagingSenderId: '485307703797',
    projectId: 'aplikasi-1dd79',
    authDomain: 'aplikasi-1dd79.firebaseapp.com',
    storageBucket: 'aplikasi-1dd79.appspot.com',
    measurementId: 'G-6TLBPX1JZ6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBkA2SEfdFmvnAcEFXzeIHrAPMzSZ3Vhpk',
    appId: '1:485307703797:android:39023380c86ce0729b00bc',
    messagingSenderId: '485307703797',
    projectId: 'aplikasi-1dd79',
    storageBucket: 'aplikasi-1dd79.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAEaW2bKGeC3ooZezdxT5Wq099bWomBj5Y',
    appId: '1:485307703797:ios:f4e7006668cf0b0b9b00bc',
    messagingSenderId: '485307703797',
    projectId: 'aplikasi-1dd79',
    storageBucket: 'aplikasi-1dd79.appspot.com',
    iosClientId:
        '485307703797-00iiuslhv5aqicvnm21biviptl0ujtn1.apps.googleusercontent.com',
    iosBundleId: 'com.example.aplikaSi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAEaW2bKGeC3ooZezdxT5Wq099bWomBj5Y',
    appId: '1:485307703797:ios:f4e7006668cf0b0b9b00bc',
    messagingSenderId: '485307703797',
    projectId: 'aplikasi-1dd79',
    storageBucket: 'aplikasi-1dd79.appspot.com',
    iosClientId:
        '485307703797-00iiuslhv5aqicvnm21biviptl0ujtn1.apps.googleusercontent.com',
    iosBundleId: 'com.example.aplikaSi',
  );
}
